### ISSUE TITLE
Deleting tunnel while pending will cause tb.jar to go create lots of tunnels

### ISSUE THREAD

**Issue by Nichol4s** [testingbot/Testingbot-Tunnel#3]
When the tunnel is in a pending state and you delete the tunnel through the API, testingbot-tunnel.jar will keep creating new tunnels until it hits the maximum amount of allowed tunnels. 

I see the following traceback: 

```
tunnel:May 31, 2013 9:03:46 AM ssh.TunnelPoller$PollTask run
tunnel:SEVERE: Unable to poll for tunnel status.
tunnel:May 31, 2013 9:03:46 AM ssh.TunnelPoller$PollTask run
tunnel:SEVERE: null
tunnel:net.sf.json.JSONException: JSONObject["state"] not found.
tunnel: at net.sf.json.JSONObject.getString(JSONObject.java:2092)
tunnel: at ssh.TunnelPoller$PollTask.run(TunnelPoller.java:34)
tunnel: at java.util.TimerThread.mainLoop(Timer.java:555)
tunnel: at java.util.TimerThread.run(Timer.java:505)
tunnel:
```

I assume that it catches the exception and than starts a new tunnel but keeps checking the old tunnel id.

**Comment by cbou** [comment]
@testingbot I still have the issue now.
